### ISSUE TITLE
無法啟動

### ISSUE THREAD

**Issue by ghost** [InterfaceGUI/DiscordGameServersStatus#1]
如需叫用 Just-In-Time (JIT) 偵錯的詳細資料，
請參閱本訊息結尾處 (而非這個對話方塊) 的資訊。

************** 例外狀況文字 **************
System.NullReferenceException: 並未將物件參考設定為物件的執行個體。
   於 DiscordGameServersStatus.DGSS.VB$StateMachine_9_MainTimer_Tick.MoveNext()
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by InterfaceGUI** [comment]
需要更詳細訊息

1. 伺服器IP部分有沒有留空?
1. 是第一次啟動嗎? 
1. 有條過時間嗎?
1. 要完整的資訊

我先推上測試修復版 請重開你的程式 左下角會顯示版本 1.4.0.8 版本 

有問題請在這篇底下回報，可以使用也請說一聲，謝謝。

一個禮拜後沒回覆會當作以解決並且關閉回復
