### ISSUE TITLE
無法獲取狀態

### ISSUE THREAD

**Issue by jlin53882** [InterfaceGUI/DiscordGameServersStatus#6]
## 描述錯誤
對bug的清晰簡潔描述。
無法獲取狀態
## 重現
請描述如何產生錯誤
ex:
1.去'discord bot 設定都有設定好，伺服器列表也有'
2.點擊'啟動'
3.點擊'立即發送訊息'
4.出現錯誤

### **貼出錯誤對話框所有文字**
```timeout: deadline has elapsed```

## 截圖
如果可以，請添加螢幕截圖以幫助解釋您的問題。
![image](https://user-images.githubusercontent.com/76562059/142760666-35c89cf5-18fc-4a45-8a9a-633c6ea658ff.png)

**附加說明**
這個IP是RADMIN VPN給的。

**Comment by InterfaceGUI** [comment]
如果是使用Radmin VPN、Hamachi 等虛擬區網軟體， [API](https://mcapi.us/) 將無法取得到你的伺服器狀態。

不過謝謝你給我了啟發，我將會新增區域網專用的功能。
