### ISSUE TITLE
無法作用

### ISSUE THREAD

**Issue by rinnyanneko** [InterfaceGUI/DiscordGameServersStatus#8]
## 描述錯誤
對bug的清晰簡潔描述。
正常運行 但是bot並未發送任何訊息(權限有給管理者了)
## 重現
請描述如何產生錯誤
ex:
1.去'...'
2.點擊'....'
3.點擊'....'
4.出現錯誤

### **貼出錯誤對話框所有文字**
```  錯誤內容這裡輸入  ```

## 截圖
如果可以，請添加螢幕截圖以幫助解釋您的問題。

**附加說明**
在此添加有關此問題的任何其他描述。

**Comment by InterfaceGUI** [comment]
請重新輸入ip與遊戲類別，如還是不行請前往電腦控制台，按下［解除安裝/變更］來將版本降低為舊版本。
這周六我才有辦法處理..

**Comment by InterfaceGUI** [comment]
我這邊已 hypixel 測試的話是正常的
![image](https://user-images.githubusercontent.com/15845368/158997319-71e34e64-b1ea-4541-8b3c-79a265c4b077.png)
請問能夠提供 你的伺服器位置以及伺服器列表 來讓我做測試嗎?

**Comment by twmccreeper** [comment]
ddtown.ddns.net

TechWolf ***@***.***>於 2022年3月18日 週五，19:45寫道：

**Comment by InterfaceGUI** [comment]
目前已經更新後的推送上去了，請您再試試看~

**Comment by InterfaceGUI** [comment]
為了避免你的伺服器位置在這被別人知道
我將你的回覆刪除

**Comment by InterfaceGUI** [comment]
如果有解決，請您告知一下，或是點選 [Close  Issues]
